name: jetx
description: Voolo - Controle financeiro e educação financeira
publish_to: 'none'

version: 1.5.0+5

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  path: ^1.9.0
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0

  # Datas, meses, formatação monetária
  intl: ^0.20.2

  # Gráficos (pizza, barras, etc.)
  fl_chart: ^0.66.0
  shared_preferences: ^2.5.4
  image_picker: ^1.1.2
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.1.0
  connectivity_plus: ^6.0.3
  http: ^1.2.2
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  in_app_purchase: ^3.2.3
  local_auth: ^2.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/local_db_seed.json
    - assets/branding/Logo_dark_slogan.png
    - assets/branding/Logo_light_slogan.png
    - assets/branding/Logo_name_light.png
    - assets/branding/logo_name_dark.png
    - assets/branding/miniatura_app.png
    - assets/branding/voolo_logo.png
